<?php

use App\Suite;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class RatesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('rates')->insert([
            [
                'suite_id'   => Suite::where('number', '=', 2)->first()->id,
                'type'       => 'rack',
                'price'      => 2340,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 2)->first()->id,
                'type'       => 'bar 1',
                'price'      => 1950,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 2)->first()->id,
                'type'       => 'bar 2',
                'price'      => 1625,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 2)->first()->id,
                'type'       => 'grupal',
                'price'      => 1070,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 5)->first()->id,
                'type'       => 'rack',
                'price'      => 2340,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 5)->first()->id,
                'type'       => 'bar 1',
                'price'      => 1950,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 5)->first()->id,
                'type'       => 'bar 2',
                'price'      => 1625,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 5)->first()->id,
                'type'       => 'grupal',
                'price'      => 1070,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 8)->first()->id,
                'type'       => 'rack',
                'price'      => 2340,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 8)->first()->id,
                'type'       => 'bar 1',
                'price'      => 1950,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 8)->first()->id,
                'type'       => 'bar 2',
                'price'      => 1625,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 8)->first()->id,
                'type'       => 'grupal',
                'price'      => 1070,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 9)->first()->id,
                'type'       => 'rack',
                'price'      => 2340,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 9)->first()->id,
                'type'       => 'bar 1',
                'price'      => 1950,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 9)->first()->id,
                'type'       => 'bar 2',
                'price'      => 1625,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 9)->first()->id,
                'type'       => 'grupal',
                'price'      => 1070,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 10)->first()->id,
                'type'       => 'rack',
                'price'      => 2340,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 10)->first()->id,
                'type'       => 'bar 1',
                'price'      => 1950,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 10)->first()->id,
                'type'       => 'bar 2',
                'price'      => 1625,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 10)->first()->id,
                'type'       => 'grupal',
                'price'      => 1070,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 15)->first()->id,
                'type'       => 'rack',
                'price'      => 2340,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 15)->first()->id,
                'type'       => 'bar 1',
                'price'      => 1950,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 15)->first()->id,
                'type'       => 'bar 2',
                'price'      => 1625,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 15)->first()->id,
                'type'       => 'grupal',
                'price'      => 1070,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 3)->first()->id,
                'type'       => 'rack',
                'price'      => 1950,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 3)->first()->id,
                'type'       => 'bar 1',
                'price'      => 1625,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 3)->first()->id,
                'type'       => 'bar 2',
                'price'      => 1354,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 3)->first()->id,
                'type'       => 'grupal',
                'price'      => 975,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 7)->first()->id,
                'type'       => 'rack',
                'price'      => 1950,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 7)->first()->id,
                'type'       => 'bar 1',
                'price'      => 1625,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 7)->first()->id,
                'type'       => 'bar 2',
                'price'      => 1354,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 7)->first()->id,
                'type'       => 'grupal',
                'price'      => 975,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 4)->first()->id,
                'type'       => 'rack',
                'price'      => 1560,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 4)->first()->id,
                'type'       => 'bar 1',
                'price'      => 1300,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 4)->first()->id,
                'type'       => 'bar 2',
                'price'      => 1083,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 4)->first()->id,
                'type'       => 'grupal',
                'price'      => 780,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 12)->first()->id,
                'type'       => 'rack',
                'price'      => 1560,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 12)->first()->id,
                'type'       => 'bar 1',
                'price'      => 1300,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 12)->first()->id,
                'type'       => 'bar 2',
                'price'      => 1083,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 12)->first()->id,
                'type'       => 'grupal',
                'price'      => 780,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 6)->first()->id,
                'type'       => 'rack',
                'price'      => 3705,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 6)->first()->id,
                'type'       => 'bar 1',
                'price'      => 3088,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 6)->first()->id,
                'type'       => 'bar 2',
                'price'      => 2573,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 6)->first()->id,
                'type'       => 'grupal',
                'price'      => 1853,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 14)->first()->id,
                'type'       => 'rack',
                'price'      => 3705,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 14)->first()->id,
                'type'       => 'bar 1',
                'price'      => 3088,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 14)->first()->id,
                'type'       => 'bar 2',
                'price'      => 2573,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 14)->first()->id,
                'type'       => 'grupal',
                'price'      => 1853,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 16)->first()->id,
                'type'       => 'rack',
                'price'      => 3705,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 16)->first()->id,
                'type'       => 'bar 1',
                'price'      => 3088,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 16)->first()->id,
                'type'       => 'bar 2',
                'price'      => 2573,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 16)->first()->id,
                'type'       => 'grupal',
                'price'      => 1853,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 11)->first()->id,
                'type'       => 'rack',
                'price'      => 2730,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 11)->first()->id,
                'type'       => 'bar 1',
                'price'      => 2275,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 11)->first()->id,
                'type'       => 'bar 2',
                'price'      => 1896,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'suite_id'   => Suite::where('number', '=', 11)->first()->id,
                'type'       => 'grupal',
                'price'      => 1365,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
